"use client";

import { useEffect, useRef, useState } from "react";

type AudioCardProps = {
  title: string;
  teachingScript: string;
};

export function AudioCard({ title, teachingScript }: AudioCardProps) {
  const [status, setStatus] = useState<"idle" | "generating" | "playing" | "fallback" | "error">("idle");
  const [message, setMessage] = useState("");
  const [hasGeneratedAudio, setHasGeneratedAudio] = useState(false);
  const audioRef = useRef<HTMLAudioElement>(null);
  const audioUrlRef = useRef<string | null>(null);

  useEffect(() => {
    return () => {
      window.speechSynthesis?.cancel();
      if (audioUrlRef.current) URL.revokeObjectURL(audioUrlRef.current);
    };
  }, []);

  function playBrowserPreview() {
    if (!window.speechSynthesis) {
      setStatus("error");
      setMessage("Audio playback is unavailable in this browser.");
      return;
    }

    window.speechSynthesis.cancel();

    const utterance = new SpeechSynthesisUtterance(teachingScript);
    utterance.rate = 0.95;
    utterance.pitch = 1;
    utterance.onend = () => setStatus("idle");
    utterance.onerror = () => setStatus("idle");

    window.speechSynthesis.speak(utterance);
    setStatus("fallback");
    setMessage("Playing the browser voice preview.");
  }

  function stopAudio() {
    window.speechSynthesis?.cancel();
    audioRef.current?.pause();
    setStatus("idle");
    setMessage("");
  }

  async function playLesson() {
    if (status === "playing" || status === "fallback") {
      stopAudio();
      return;
    }

    if (audioRef.current?.src) {
      try {
        await audioRef.current.play();
        setStatus("playing");
        setMessage("Playing AI-generated audio.");
      } catch {
        setStatus("error");
        setMessage("Audio could not start. Try the browser voice preview.");
      }
      return;
    }

    setStatus("generating");
    setMessage("Generating AI audio from this teaching script...");

    try {
      const response = await fetch("/api/audio", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ teachingScript }),
      });

      if (!response.ok) {
        playBrowserPreview();
        return;
      }

      const url = URL.createObjectURL(await response.blob());
      if (audioUrlRef.current) URL.revokeObjectURL(audioUrlRef.current);
      audioUrlRef.current = url;

      if (!audioRef.current) throw new Error("Audio player is unavailable.");
      audioRef.current.src = url;
      audioRef.current.load();
      setHasGeneratedAudio(true);
      await audioRef.current.play();
      setStatus("playing");
      setMessage("Playing AI-generated audio.");
    } catch {
      playBrowserPreview();
    }
  }

  return (
    <aside className="audio-card">
      <div className="audio-kicker">Listen to this lesson</div>
      <h2>{title}</h2>
      <p>
        Generate spoken audio from this episode&apos;s dedicated teaching script.
      </p>
      <button
        className={`play-button ${status === "playing" || status === "fallback" ? "active" : ""}`}
        onClick={playLesson}
        type="button"
        disabled={status === "generating"}
      >
        {status === "generating"
          ? "Preparing audio..."
          : status === "playing" || status === "fallback"
            ? "■  Stop lesson"
            : "▶  Generate & play lesson"}
      </button>
      <div className="audio-progress" aria-hidden="true"><span /></div>
      <div className="audio-caption">AI-generated voice · browser preview fallback</div>
      <p className="audio-disclosure">Audio is generated by AI.</p>
      {message ? <p className="audio-status" role="status">{message}</p> : null}
      {hasGeneratedAudio ? (
        <audio
          className="audio-player"
          controls
          onEnded={() => { setStatus("idle"); setMessage(""); }}
          onPause={() => setStatus((current) => current === "playing" ? "idle" : current)}
          ref={audioRef}
        />
      ) : <audio ref={audioRef} />}
      <details className="lesson-script">
        <summary>View teaching script</summary>
        <p>{teachingScript}</p>
      </details>
    </aside>
  );
}
